version: 2

models:
  - name: stg_fact_daily_prices
    columns:
      - name: ticker
        tests:
          - not_null

      - name: trade_date
        tests:
          - not_null

      - name: open_price
        tests:
          - not_null

      - name: close_price
        tests:
          - not_null

      - name: high_price
        tests:
          - not_null

      - name: low_price
        tests:
          - not_null

      - name: volume
        tests:
          - not_null