sb_finance_project:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: gobierno_datos_olap
      host: localhost
      port: 8123
      user: default
      password: clickhouse123
      secure: false
      verify: false
      retries: 1
      connect_timeout: 10